# generated by datamodel-codegen:
#   timestamp: 2024-04-28T19:06:26+00:00
#   k8s version: v1.30.0

from __future__ import annotations

from pydantic import BaseModel


class RawExtension(BaseModel):
    pass
